### PR TITLE
Upgrade Django and all its dependencies.

### PR DESCRIPTION
**Pull request by attiyaIshaque**
### Description

Update Django. 
Older version: 1.8.7
New version: 1.11.5

This also includes a small change to cover implementation of url patterns. 

### Reviewers
- [ ] @ssemenova 
- [ ] @fysheets 
- [ ] @awaisdar001  
 
### Post-review
- [ ] Rebase and squash commits

### CODE REVIEW

**Comment by awaisdar001** [comment]
Looks good to me!

Question: Do we need a release tag for this as well?

**Comment by attiyaIshaque** [comment]
@awaisdar001 we don't need a release tag for this. (i think so) :)

**Comment by nedbat** [comment]
This has been cherry-picked onto Hawthorn.

**Comment by attiyaIshaque** [comment]
@nedbat do you have any idea when will this fix goes live?

**Comment by nedbat** [comment]
@attiyaIshaque live in edX production? I have no idea.  We are going to ship Hawthorn this week, and people will start running it.

**Pull request merged**
