### PR TITLE
make pii_report directory name consistent

### PR DESCRIPTION
**Pull request by pwnage101**
The pii_* make targets use "pii_report" instead of "pii_reports".

### CODE REVIEW

**Comment by doctoryes** [comment]
Did you want to add `pii_report` to `.gitignore` as well?

**Comment by doctoryes** [comment]
Also, the `Makefile` has the name defined separately - for the purpose of re-creating the correct directory.

**Comment by pwnage101** [comment]
> Did you want to add pii_report to .gitignore as well?

I'll add that too.  This PR was initially generated with github's web UI so it wasn't possible the first time around.

> Also, the Makefile has the name defined separately - for the purpose of re-creating the correct directory.

Can you elaborate?  Was the directory name in the makefile supposed to be different than the one in the config file?

**Comment by doctoryes** [comment]
No - the directory name was supposed to be the same. I passed the name on the cmd-line in `Makefile` so it could be easily seen that the cleaning of the PII reports was done in the same directory as the generated reports.

**Comment by pwnage101** [comment]
Forgot I had this PR lingering around.

**Pull request merged**
