### PR TITLE
Adding format tag instead of Klass and span for ES highlight.

### PR DESCRIPTION
**Pull request by muzaffaryousaf**
This PR replaces html tag & class being with format tags`{elasticsearch_highlight_start}`, `{elasticsearch_highlight_end}` for ES highlight feature.

 TNL-4012

### CODE REVIEW

**Comment by muzaffaryousaf** [comment]
@robrap Here is the relevant changes in edx-notes-api, this also includes the python tests that you mentioned on edx-platform's PR. Thanks.

**Comment by robrap** [comment]
:+1:

**Comment by muzaffaryousaf** [comment]
@symbolist Would you mind to give it a quick look ? Thanks.

**Comment by symbolist** [comment]
:+1:

**Pull request merged**
