### PR TITLE
Update openedx.yaml

### PR DESCRIPTION
**Pull request by feanil**
Update owner to Bill

### CODE REVIEW

**Comment by feanil** [comment]
This needs an owner so that it can keep getting regular security updates.  Bill was interested in owning this.  Starting  a conversation.

**Comment by bderusha** [comment]
I agree to own this service as I consider it under "active development" from the Platform Health squad while we transition it to run on k8s infrastructure

**Comment by feanil** [comment]
@bderusha do you want to wait for a response from @e0d or should we just merge this?

**Comment by bderusha** [comment]
I am comfortable merging this.  If @e0d thinks this is the wrong choice we can always update

**Pull request merged**
