### PR TITLE
 Modifying .travis.yml to more match psudo-standard 

### PR DESCRIPTION
**Pull request by jinder1s**
Changed how the test matrix is created by specifying confi in python and env tag
Added django30 to testing

I'm calling it psuedo-standard cause it has not been agreed upon, its just the norm among our repos.

### CODE REVIEW

**Comment by morenol** [comment]
Hi @jinder1s, if we apply these changes, internally all the tests will be run in python3.6

You can check this in the output of the tests:
```
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
```

**Comment by jinder1s** [comment]
@morenol thanks for pointing out the python 3.6.9 issue. Question, do you know why is that happening? Is this cause this is using docker?

**Comment by morenol** [comment]
>  Question, do you know why is that happening? Is this cause this is using docker?

Yes, it is due to it using the docker image so it ignores the python version of the travis worker. It is using the default python interpreter in the docker container.

 For that reason we had to use 
        `TOXENV=py38-django22`

**Comment by jinder1s** [comment]
okay, makes sense, thanks for the info!

**Comment by jinder1s** [comment]
Closing this PR since this repo's travis testing is different from the usual, thus the diverging format.

**Pull request closed without merging**
