### PR TITLE
Updated the Dockerfile to use python 3.8

### PR DESCRIPTION
**Pull request by mraarif**
Relevant JIRA issue here: https://openedx.atlassian.net/browse/BOM-2032 (also https://openedx.atlassian.net/browse/BOM-1965)
ref: [edx/configuration#5968](https://github.com/edx/configuration/pull/5968)

### CODE REVIEW

**Review by awais786 — APPROVED** [review]

**Review by UsamaSadiq — APPROVED** [review]

**Comment by mraarif** [comment]
I tested these changes by building an image locally.

**Review by adzuci — APPROVED** [review]
LGTM

**Comment by edx-deployment** [comment]
GitHub Actions has started building this code into a docker file.  Check status at https://github.com/edx/edx-notes-api/actions/runs/273024595

**Comment by edx-deployment** [comment]
A docker container including this PR has been built and shipped to docker hub.  Check it out at https://hub.docker.com/r/openedx/edx-notes-api/tags?page=1&name=6e339b1bbbb421efe52cb7737be4b61651a594a4

**Pull request merged**
