### PR TITLE
Adding option.txt back to fix the broken named release.

### PR DESCRIPTION
**Pull request by muzaffaryousaf**

### CODE REVIEW

**Comment by muzaffaryousaf** [comment]
@symbolist @nedbat Should we merge this ??

**Comment by symbolist** [comment]
I do not see any harm in keeping the file but maybe @nedbat has a better suggestion for the comment.

**Comment by symbolist** [comment]
:+1:

**Comment by nedbat** [comment]
I just commented on the original PR that we should hold off on this.  It won't fix the real problem (using master of this repo with Dogwood of everything else).  I'll fix the Dogwood install, and maybe we'll come back to this.  Thanks.

**Comment by jibsheet** [comment]
I note that newrelic should be optional, there are people who will run notes but not use New Relic to monitor.

See for examples
credentials/requirements/optional.txt:newrelic==2.56.0.42
ecommerce-worker/requirements/optional.txt:newrelic==2.54.0.41
ecommerce/requirements/optional.txt:newrelic==2.58.2.45
edx-analytics-dashboard/requirements/optional.txt:newrelic==2.40.0.34             # New Relic
edx-analytics-data-api/requirements/optional.txt:newrelic==2.40.0.34
programs/requirements/optional.txt:newrelic==2.56.0.42

**Comment by muzaffaryousaf** [comment]
@jibsheet We are using new relic in api to monitor the usage, in that case the code would be broken if someone don't install new relic. I think it makes more sense to move it to base.txt, as it's in edx-platform repo.

**Comment by nedbat** [comment]
@muzaffaryousaf Maybe I don't understand everything here, but New Relic is a paid service, isn't it? We can't assume that every Open edX adopter that wants to use this API will be paying for New Relic.  edx-platform has some way of conditionalizing the use of the service, don't they?

**Comment by muzaffaryousaf** [comment]
@nedbat Good point. I'm not aware of any conditional usage of new relic in edx-platform, Also, i don't see any code references in any of the above mentioned repos.

**Comment by jibsheet** [comment]
@muzaffaryousaf I see now that I have grepped your code base what you are trying to say, would have been nice if the commit which moved newrelic from optional.txt to base.txt had included this rationale, rather than just "[TNL-4029] user can't add more than maximum number of allowed annotations" which is not really helpful to anyone digging in git history.

**Comment by nedbat** [comment]
New relic is a no-op if it is not configured, so it's fine to install this from base.txt.

**Comment by edx-webhook** [comment]
Thanks for the pull request, @muzaffaryousaf! I've created [OSPR-2119](https://openedx.atlassian.net/browse/OSPR-2119) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-notes-api/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Pull request closed without merging**
