### PR TITLE
Revert "[BB-724] Disable default BasicAuthentication "

### PR DESCRIPTION
**Pull request by bderusha**
Reverts edx/edx-notes-api#85

### CODE REVIEW

**Comment by ormsbee** [comment]
@xitij2000: Heads up on this revert -- when we finally released a new version of Notes with this change in it, we got a slew of auth related errors.

**Comment by ormsbee** [comment]
@bderusha: Can you paste in the errors you were seeing?

**Comment by xitij2000** [comment]
@ormsbee Perhaps we can make this configurable, and keep ``BasicAuthentication`` enabled by default? Adding this option will break the API in our use case. 

I'm not sure I understand why removing it would cause issues though, since the API doesn't authenticate using basic auth.

**Comment by ormsbee** [comment]
@xitij2000: Sorry for the slow replies. I've been sick as of late.

It looks like this was a red herring on our part, so I'm reverting the revert (i.e. keeping your contribution from #85). Apologies for the trouble.

**Comment by xitij2000** [comment]
@ormsbee No worries. I hope you're feeling better now!

**Pull request merged**
