### PR TITLE
standardize GH actions

### PR DESCRIPTION
**Pull request by syed-awais-ali**

### CODE REVIEW

**Review by nadeemshahzad — APPROVED** [review]

**Comment by edx-deployment** [comment]
GitHub Actions has started building this code into a docker file.  Check status at https://github.com/edx/edx-notes-api/actions/runs/247803253

**Comment by edx-deployment** [comment]
A docker container including this PR has been built and shipped to docker hub.  Check it out at https://hub.docker.com/r/openedx/edx-notes-api/tags?page=1&name=8ee12b908a5d16cf36af1e86f45e634177912d54

**Comment by edx-deployment** [comment]
GitHub Actions has started building this code into a docker file.  Check status at https://github.com/edx/edx-notes-api/actions/runs/247803253

**Comment by edx-deployment** [comment]
A docker container including this PR has been built and shipped to docker hub.  Check it out at https://hub.docker.com/r/openedx/edx-notes-api/tags?page=1&name=8ee12b908a5d16cf36af1e86f45e634177912d54

**Pull request merged**
